GAPSoft/Models/PedidosClientes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using System.Linq;
using System.Web;

namespace GAPSoft.Models
{
    public class PedidosClientes
    {
        public int ID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Fecha { get; set; }

        [DisplayName("Fecha de Entrega")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaEntrega { get; set; }

        [Range(1,999999999)]
        [DataType(DataType.Currency, ErrorMessage= "El Campo solo permite Números")]
        public float Abono { get; set; }

        [DisplayName("Valor Total")]
        [Range(1, 999999999)]
        [DataType(DataType.Currency, ErrorMessage = "El Campo solo permite Números")]
        public float ValorTotal { get; set; }

        [DisplayName("Cliente")]
        public int ClientesID  { get; set; }


        public int EstadosPedidoID { get; set; }
        

        public virtual Clientes Cliente { get; set; }
        public virtual EstadosPedidos EstadoPedido{ get; set; }

        
    }
}

GAPSoft/Controllers/PedidosClientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GAPSoft.DAL;
using GAPSoft.Models;
using PagedList;

namespace GAPSoft.Controllers
{
    public class PedidosClientesController : Controller
    {
        private GATSoftContext db = new GATSoftContext();

        // GET: PedidosClientes
        public ActionResult Index(string BuscarNombre,string currentFilter, int? page)
        {
            if (BuscarNombre != null)
            {
                page = 1;
            }
            else
            {
                BuscarNombre = currentFilter;
            }

            ViewBag.CurrentFilter = BuscarNombre;
            
            
          var pedidosClientes = db.PedidosClientes.Include(p => p.Cliente);
            if(!string.IsNullOrEmpty(BuscarNombre)) 
            {
                //pedidosClientes = pedidosClientes.Where(p => p.Cliente.Nombres.Contains(BuscarNombre));
            }
            return View(pedidosClientes.ToList());
            //int pageSize = 5;
            //int pageNumber = (page ?? 1);
            //return View(pedidosClientes.ToPagedList(pageNumber, pageSize));
        }

        // GET: PedidosClientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidosClientes pedidosClientes = db.PedidosClientes.Find(id);
            if (pedidosClientes == null)
            {
                return HttpNotFound();
            }
            return View(pedidosClientes);
        }

        // GET: PedidosClientes/Create
        public ActionResult Create()
        {
            ViewBag.ClientesID = new SelectList(db.Clientes, "ID", "Nombres");
            return View();
        }

        // POST: PedidosClientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Fecha,FechaEntrega,Abono,ValorTotal,ClientesID,EstadosPedidoID")] PedidosClientes pedidosClientes)
        {
            if (ModelState.IsValid)
            {
                db.PedidosClientes.Add(pedidosClientes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientesID = new SelectList(db.Clientes, "ID", "Nombres", pedidosClientes.ClientesID);
            return View(pedidosClientes);
        }

        // GET: PedidosClientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidosClientes pedidosClientes = db.PedidosClientes.Find(id);
            if (pedidosClientes == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientesID = new SelectList(db.Clientes, "ID", "Nombres", pedidosClientes.ClientesID);
            return View(pedidosClientes);
        }

        // POST: PedidosClientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Fecha,FechaEntrega,Abono,ValorTotal,ClientesID,EstadosPedidoID")] PedidosClientes pedidosClientes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedidosClientes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClientesID = new SelectList(db.Clientes, "ID", "Nombres", pedidosClientes.ClientesID);
            return View(pedidosClientes);
        }

        // GET: PedidosClientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidosClientes pedidosClientes = db.PedidosClientes.Find(id);
            if (pedidosClientes == null)
            {
                return HttpNotFound();
            }
            return View(pedidosClientes);
        }

        // POST: PedidosClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PedidosClientes pedidosClientes = db.PedidosClientes.Find(id);
            db.PedidosClientes.Remove(pedidosClientes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GAPSoft/Views/PedidosClientes/Create.cshtml
@model GAPSoft.Models.PedidosClientes

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PedidosClientes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEntrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientesID, "ClientesID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientesID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientesID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadosPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadosPedidoID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadosPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GAPSoft/Views/PedidosClientes/Delete.cshtml
@model GAPSoft.Models.PedidosClientes

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PedidosClientes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEntrega)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadosPedidoID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadosPedidoID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GAPSoft/Views/PedidosClientes/Details.cshtml
@model GAPSoft.Models.PedidosClientes

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PedidosClientes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEntrega)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEntrega)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Abono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Abono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadosPedidoID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadosPedidoID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GAPSoft/Views/PedidosClientes/Edit.cshtml
@model GAPSoft.Models.PedidosClientes

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PedidosClientes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEntrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientesID, "ClientesID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientesID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientesID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadosPedidoID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadosPedidoID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadosPedidoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GAPSoft/Views/PedidosClientes/Index.cshtml
@model PagedList.IPagedList<GAPSoft.Models.PedidosClientes>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Pedidos de los Clientes</h2>

<p>
    @Html.ActionLink("Nuevo Pedido", "Create")
</p>

@using (Html.BeginForm("Index", "PedidosClientes", FormMethod.Get))
{
    <p>
        Filtrar por Nombre: @Html.TextBox("BuscarNombre", ViewBag.CurrentFilter as string)
        <input type="submit" value="Buscar" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Cliente.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().FechaEntrega)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Abono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ValorTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().EstadosPedidoID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaEntrega)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Abono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorTotal)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.ID }) |
            @Html.ActionLink("Cancelar", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }))